name: Test Suite

on:
  push:
  pull_request:

jobs:
  php_tests:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        php: [7.4, 7.3]

    name: PHP ${{ matrix.php }}

    steps:
      - name: Checkout code
        uses: actions/checkout@v1

      - name: Setup PHP
        uses: shivammathur/setup-php@v1
        with:
          php-version: ${{ matrix.php }}
          extensions: dom, curl, libxml, mbstring, zip, pcntl, pdo, sqlite, pdo_sqlite, bcmath, soap, intl, gd, exif, iconv, imagick
          coverage: none

      - name: Install dependencies
        run: |
          composer validate
          composer install --no-interaction

      - name: Run PHPUnit
        run: composer test
